name: mini_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  logger: ^2.5.0
  provider: ^6.1.2
  get_it: ^8.0.2
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  fade_shimmer: ^2.2.0
  shimmer: ^3.0.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  device_preview: ^1.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  sign_in_button: ^3.2.0
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  permission_handler: ^11.4.0
  firebase_app_check: ^0.3.2+4
  shared_preferences: ^2.5.2
  flutter_stripe: ^11.4.0
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
