// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIO0TDbJMYAYVX1w_FVmFrQix6SRWWw8g',
    appId: '1:407198618069:web:3af52454974b6cf1a66d5c',
    messagingSenderId: '407198618069',
    projectId: 'miniecommerceeapp',
    authDomain: 'miniecommerceeapp.firebaseapp.com',
    storageBucket: 'miniecommerceeapp.firebasestorage.app',
    measurementId: 'G-N5FQ2LLW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxKhwfWcMCZxGAhTjHfEPZqXWAcIq0QE',
    appId: '1:407198618069:android:bcf37d04080c9820a66d5c',
    messagingSenderId: '407198618069',
    projectId: 'miniecommerceeapp',
    storageBucket: 'miniecommerceeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbfG8zLWV-071ZhfJgrJdzW-s3cTfnNE',
    appId: '1:407198618069:ios:f49bd7089a68fcb8a66d5c',
    messagingSenderId: '407198618069',
    projectId: 'miniecommerceeapp',
    storageBucket: 'miniecommerceeapp.firebasestorage.app',
    androidClientId: '407198618069-q5763l851dfn3ht24m42dlkossq3rmof.apps.googleusercontent.com',
    iosClientId: '407198618069-3k62gq6f3ukkgrp5ngrnh73mtse6apkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbfG8zLWV-071ZhfJgrJdzW-s3cTfnNE',
    appId: '1:407198618069:ios:f49bd7089a68fcb8a66d5c',
    messagingSenderId: '407198618069',
    projectId: 'miniecommerceeapp',
    storageBucket: 'miniecommerceeapp.firebasestorage.app',
    androidClientId: '407198618069-q5763l851dfn3ht24m42dlkossq3rmof.apps.googleusercontent.com',
    iosClientId: '407198618069-3k62gq6f3ukkgrp5ngrnh73mtse6apkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIO0TDbJMYAYVX1w_FVmFrQix6SRWWw8g',
    appId: '1:407198618069:web:1843dc8669f40831a66d5c',
    messagingSenderId: '407198618069',
    projectId: 'miniecommerceeapp',
    authDomain: 'miniecommerceeapp.firebaseapp.com',
    storageBucket: 'miniecommerceeapp.firebasestorage.app',
    measurementId: 'G-0M0T5XE4VD',
  );
}
